name: 'Rclone S3 Config'
description: 'Rclone S3 Config'
inputs:
  aws_region:
    description: 'AWS region'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rclone
      shell: bash
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Setup Rclone
      shell: bash
      run: |
        rclone config create dest s3 \
        provider=AWS \
        env_auth=true \
        region=${{ inputs.aws_region }}
