name: 'S3 Sync with Rclone'
description: 'Sync files to S3 using rclone'
inputs:
  source_dir:
    description: 'Local directory to sync'
    required: true
  s3_bucket:
    description: 'S3 bucket name with optional path (e.g. "my-bucket/static")'
    required: true
  aws_region:
    description: 'AWS region (e.g. "us-east-1")'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rclone
      shell: bash
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone
      shell: bash
      run: |
        mkdir -p ~/.config/rclone
        echo "[s3]
        type = s3
        provider = AWS
        access_key_id = ${{ env.AWS_ACCESS_KEY_ID }}
        secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
        region = ${{ inputs.aws_region }}
        " > ~/.config/rclone/rclone.conf

    - name: Sync files to S3
      shell: bash
      run: |
        rclone sync ${{ inputs.source_dir }} s3:${{ inputs.s3_bucket }} \
          --checksum \
          --verbose