name: "Build and Test .NET application"

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Install dependencies
        run: dotnet restore ${{ inputs.project_path }}

      # - name: Build
      #   run: |
      #     dotnet build ${{ inputs.project_path }} --configuration Release --no-restore

      - name: Test        
        id: tests
        continue-on-error: true
        run: |
          #cd ./tests/unit/fintech.core.auth.tests
          dotnet build -c Release
          # dotnet test --configuration Release --results-directory "TestResults" \
          #   --settings cover.runsettings --collect:"XPlat Code Coverage" --no-build \
          #   --no-restore 2>&1 | tee test_output.txt

          dotnet test --configuration Release --results-directory "TestResults" --collect:"XPlat Code Coverage" \
            --no-build --no-restore 2>&1 | tee test_output.txt
          
          # multi-line output
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat test_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - uses: actions/github-script@v8
        env:
          BODY: ${{ steps.tests.outputs.body }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const body = `**Test Output**
            \`\`\`
            ${process.env.BODY}
            \`\`\``

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })
