name: Build NuGet packages

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: true
      dotnet_version:
        required: false
        type: string
        default: "8.0.x"
      project_path:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      - run: dotnet build ${{ inputs.project_path }} -c Release

  publish:
    needs: [build]
    if: ${{ success() && inputs.publish }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      - run: |
          dotnet pack ${{ inputs.project_path }} --configuration=Release --output artifacts --include-source
      - run: dotnet nuget push artifacts/*.nupkg --api-key ${{ github.token }} --skip-duplicate
