### Required Pre configured IAM Role credentials with Trust relationship with GitHub and permission policy to PutObject to S3.
name: Upload Django Static Files to S3

on:
  push:
    branches:
      - main

# permissions:
#   id-token: write   # Required for OIDC

jobs:
  upload-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws-cn:iam::123456789100:role/my-github-actions-role"
          aws-region: "us-east-1"
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Rclone Setup
        uses: dashdevs/actions/.github/actions/rclone-setup@develop
        with:
          aws_region: "us-east-1"

      - name: Sync static files to S3
        uses: dashdevs/actions/.github/actions/rclone-sync@develop
        with:
          source_dir: "./static/" # directory generated by the collectstatic module for django applicaton
          s3_bucket: "<bucket-name>/static"